### ISSUE TITLE
Update documentation: Fork CLI is required

### ISSUE THREAD

**Issue by ghost** [gwhobbs/OpenInFork.novaextension#1]
Hi, thanks for this extension 😄 

Just a small change to documentation is needed: it's not enough to simply have Fork installed, you have the have the CLI tools installed, as well, otherwise `which` will return no results, and you'll be prompted to install Fork.

**Comment by diidiiman** [comment]
For someone struggling to locate this CLI tools:
They are located in Fork App in `Preferences -> Integration`

**Comment by gwhobbs** [comment]
Thanks! Added to readme.
